In [1]:
import pandas as pd
import numpy as np
from pybaseball import statcast

In [2]:
df = statcast('2026-06-09', '2026-06-09').reset_index(drop=True)

This is a large query, it may take a moment to complete

100%|██████████| 1/1 [00:00<00:00,  8.42it/s]

In [51]:
cols = [
    'pitch_type',
    'game_date',
    'release_speed',
    'release_pos_x',
    'release_pos_z',
    'player_name',
    'batter',
    'pitcher',
    'inning',
    'inning_topbot',
    'events',
    'description',
    'woba_value',
    'woba_denom',
    'home_team',
    'away_team',
    'home_win_exp'
]

In [52]:
df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,home_win_exp_diff
0,FF,2026-06-09,95.4,-2.4,5.87,"Barnett, Mason",694192,686930,field_out,hit_into_play,...,1.44,-0.34,-0.34,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,FF,2026-06-09,96.5,-2.31,5.83,"Barnett, Mason",694192,686930,NaN,ball,...,1.65,0.28,0.28,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.008
2,FF,2026-06-09,96.4,-2.38,5.9,"Barnett, Mason",694192,686930,NaN,ball,...,1.67,0.17,0.17,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.003
3,FF,2026-06-09,96.5,-2.21,5.88,"Barnett, Mason",694192,686930,NaN,ball,...,1.75,-0.02,-0.02,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.001
4,SL,2026-06-09,88.9,-2.15,6.14,"Barnett, Mason",694192,686930,NaN,foul,...,2.8,-0.28,-0.28,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.002

In [53]:
df.columns.to_list()

['pitch_type',
 'game_date',
 'release_speed',
 'release_pos_x',
 'release_pos_z',
 'player_name',
 'batter',
 'pitcher',
 'events',
 'description',
 'spin_dir',
 'spin_rate_deprecated',
 'break_angle_deprecated',
 'break_length_deprecated',
 'zone',
 'des',
 'game_type',
 'stand',
 'p_throws',
 'home_team',
 'away_team',
 'type',
 'hit_location',
 'bb_type',
 'balls',
 'strikes',
 'game_year',
 'pfx_x',
 'pfx_z',
 'plate_x',
 'plate_z',
 'on_3b',
 'on_2b',
 'on_1b',
 'outs_when_up',
 'inning',
 'inning_topbot',
 'hc_x',
 'hc_y',
 'tfs_deprecated',
 'tfs_zulu_deprecated',
 'umpire',
 'sv_id',
 'vx0',
 'vy0',
 'vz0',
 'ax',
 'ay',
 'az',
 'sz_top',
 'sz_bot',
 'hit_distance_sc',
 'launch_speed',
 'launch_angle',
 'effective_speed',
 'release_spin_rate',
 'release_extension',
 'game_pk',
 'fielder_2',
 'fielder_3',
 'fielder_4',
 'fielder_5',
 'fielder_6',
 'fielder_7',
 'fielder_8',
 'fielder_9',
 'release_pos_y',
 'estimated_ba_using_speedangle',
 'estimated_woba_using_speedangle',
 'woba_value',
 'woba_denom',
 'babip_value',
 'iso_value',
 'launch_speed_angle',
 'at_bat_number',
 'pitch_number',
 'pitch_name',
 'home_score',
 'away_score',
 'bat_score',
 'fld_score',
 'post_away_score',
 'post_home_score',
 'post_bat_score',
 'post_fld_score',
 'if_fielding_alignment',
 'of_fielding_alignment',
 'spin_axis',
 'delta_home_win_exp',
 'delta_run_exp',
 'bat_speed',
 'swing_length',
 'miss_distance',
 'estimated_slg_using_speedangle',
 'delta_pitcher_run_exp',
 'hyper_speed',
 'home_score_diff',
 'bat_score_diff',
 'home_win_exp',
 'bat_win_exp',
 'age_pit_legacy',
 'age_bat_legacy',
 'age_pit',
 'age_bat',
 'n_thruorder_pitcher',
 'n_priorpa_thisgame_player_at_bat',
 'pitcher_days_since_prev_game',
 'batter_days_since_prev_game',
 'pitcher_days_until_next_game',
 'batter_days_until_next_game',
 'api_break_z_with_gravity',
 'api_break_x_arm',
 'api_break_x_batter_in',
 'arm_angle',
 'attack_angle',
 'attack_direction',
 'swing_path_tilt',
 'intercept_ball_minus_batter_pos_x_inches',
 'intercept_ball_minus_batter_pos_y_inches',
 'home_win_exp_diff']

In [54]:
df[cols]

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,inning,inning_topbot,events,description,woba_value,woba_denom,home_team,away_team,home_win_exp
0,FF,2026-06-09,95.4,-2.4,5.87,"Barnett, Mason",694192,686930,9,Top,field_out,hit_into_play,0.0,1,ATH,MIL,0.978
1,FF,2026-06-09,96.5,-2.31,5.83,"Barnett, Mason",694192,686930,9,Top,NaN,ball,<NA>,<NA>,ATH,MIL,0.986
2,FF,2026-06-09,96.4,-2.38,5.9,"Barnett, Mason",694192,686930,9,Top,NaN,ball,<NA>,<NA>,ATH,MIL,0.989
3,FF,2026-06-09,96.5,-2.21,5.88,"Barnett, Mason",694192,686930,9,Top,NaN,ball,<NA>,<NA>,ATH,MIL,0.99
4,SL,2026-06-09,88.9,-2.15,6.14,"Barnett, Mason",694192,686930,9,Top,NaN,foul,<NA>,<NA>,ATH,MIL,0.988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4681,FF,2026-06-09,98.0,-1.81,6.33,"Cease, Dylan",656941,656302,1,Top,NaN,ball,<NA>,<NA>,TOR,PHI,0.503
4682,SL,2026-06-09,88.8,-1.93,6.05,"Cease, Dylan",656941,656302,1,Top,NaN,ball,<NA>,<NA>,TOR,PHI,0.507
4683,SL,2026-06-09,88.3,-1.53,6.19,"Cease, Dylan",656941,656302,1,Top,NaN,foul_tip,<NA>,<NA>,TOR,PHI,0.501
4684,CH,2026-06-09,85.4,-1.42,6.24,"Cease, Dylan",656941,656302,1,Top,NaN,ball,<NA>,<NA>,TOR,PHI,0.503
4685,SL,2026-06-09,86.0,-1.66,6.2,"Cease, Dylan",656941,656302,1,Top,NaN,foul,<NA>,<NA>,TOR,PHI,0.5

In [55]:
df['home_win_exp_diff'] = df.groupby(['game_pk', 'inning', 'inning_topbot'])['home_win_exp'].diff().abs()

In [56]:
cols.append('home_win_exp_diff')

In [57]:
df.sort_values('home_win_exp_diff',ascending=False)[cols]

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,inning,inning_topbot,events,description,woba_value,woba_denom,home_team,away_team,home_win_exp,home_win_exp_diff
314,SL,2026-06-09,90.4,-1.44,5.89,"Garcia, Rico",668227,670329,10,Top,home_run,hit_into_play,2.0,1,BAL,SEA,0.516,0.44
3482,CH,2026-06-09,89.7,-0.65,5.91,"Rodriguez, Bradgley",553993,699134,10,Top,double,hit_into_play,1.25,1,SD,CIN,0.516,0.398
330,SI,2026-06-09,99.8,2.81,5.77,"Ferrer, José A.",694212,678606,9,Bot,fielders_choice,hit_into_play,0.9,1,BAL,SEA,0.426,0.398
4429,FF,2026-06-09,99.8,-2.97,5.24,"Varland, Louis",681082,686973,9,Top,double,hit_into_play,1.25,1,TOR,PHI,0.549,0.374
297,SL,2026-06-09,88.5,-1.77,5.77,"Davila, Nick",665750,689546,10,Bot,single,hit_into_play,0.9,1,BAL,SEA,0.285,0.362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4606,SI,2026-06-09,97.1,-1.23,6.24,"Cease, Dylan",607208,656302,3,Top,field_out,hit_into_play,0.0,1,TOR,PHI,0.426,<NA>
4614,SI,2026-06-09,95.2,-1.75,4.82,"Wheeler, Zack",807727,554430,2,Bot,strikeout,swinging_strike,0.0,1,TOR,PHI,0.43,<NA>
4629,FF,2026-06-09,97.4,-1.28,6.25,"Cease, Dylan",666969,656302,2,Top,strikeout,swinging_strike,0.0,1,TOR,PHI,0.434,<NA>
4642,FC,2026-06-09,91.2,-2.05,4.92,"Wheeler, Zack",660821,554430,1,Bot,force_out,hit_into_play,0.0,1,TOR,PHI,0.413,<NA>
4664,SI,2026-06-09,95.8,-1.46,6.08,"Cease, Dylan",664761,656302,1,Top,strikeout,swinging_strike,0.0,1,TOR,PHI,0.427,<NA>

In [58]:
df['home_win_exp_diff'].idxmax()

314

In [59]:
from pybaseball import playerid_reverse_lookup

In [60]:
playerid_reverse_lookup([668227])

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,arozarena,randy,668227,arozr001,arozara01,19290,2019.0,2026.0

In [61]:
df.iloc[305:320][cols]

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,inning,inning_topbot,events,description,woba_value,woba_denom,home_team,away_team,home_win_exp,home_win_exp_diff
305,CH,2026-06-09,85.2,-1.65,5.77,"Garcia, Rico",686527,670329,10,Top,field_out,hit_into_play,0.0,1,BAL,SEA,0.191,0.101
306,FF,2026-06-09,96.1,-1.7,5.84,"Garcia, Rico",686527,670329,10,Top,NaN,ball,<NA>,<NA>,BAL,SEA,0.193,0.002
307,CH,2026-06-09,86.4,-1.67,5.71,"Garcia, Rico",686527,670329,10,Top,NaN,ball,<NA>,<NA>,BAL,SEA,0.194,0.001
308,SL,2026-06-09,88.4,-1.45,5.85,"Garcia, Rico",686527,670329,10,Top,NaN,foul,<NA>,<NA>,BAL,SEA,0.194,0.0
309,CH,2026-06-09,85.1,-1.75,5.81,"Garcia, Rico",686527,670329,10,Top,NaN,swinging_strike,<NA>,<NA>,BAL,SEA,0.191,0.003
310,CH,2026-06-09,85.3,-1.47,5.83,"Garcia, Rico",686527,670329,10,Top,NaN,called_strike,<NA>,<NA>,BAL,SEA,0.084,0.107
311,CH,2026-06-09,85.3,-1.62,5.83,"Garcia, Rico",647304,670329,10,Top,field_out,hit_into_play,0.0,1,BAL,SEA,0.173,0.089
312,FF,2026-06-09,95.4,-1.38,5.9,"Garcia, Rico",647304,670329,10,Top,NaN,called_strike,<NA>,<NA>,BAL,SEA,0.169,0.004
313,FF,2026-06-09,96.2,-1.4,5.89,"Garcia, Rico",647304,670329,10,Top,NaN,ball,<NA>,<NA>,BAL,SEA,0.076,0.093
314,SL,2026-06-09,90.4,-1.44,5.89,"Garcia, Rico",668227,670329,10,Top,home_run,hit_into_play,2.0,1,BAL,SEA,0.516,0.44
315,FF,2026-06-09,94.3,-1.08,6.09,"Garcia, Rico",668227,670329,10,Top,NaN,called_strike,<NA>,<NA>,BAL,SEA,0.333,0.183
316,SI,2026-06-09,100.0,2.7,5.71,"Ferrer, José A.",624413,678606,9,Bot,force_out,hit_into_play,0.0,1,BAL,SEA,0.715,<NA>
317,SI,2026-06-09,99.5,2.65,5.7,"Ferrer, José A.",624413,678606,9,Bot,NaN,ball,<NA>,<NA>,BAL,SEA,0.64,0.075
318,SI,2026-06-09,99.1,2.68,5.66,"Ferrer, José A.",624413,678606,9,Bot,NaN,foul,<NA>,<NA>,BAL,SEA,0.64,0.0
319,SI,2026-06-09,99.4,2.76,5.67,"Ferrer, José A.",624413,678606,9,Bot,NaN,foul,<NA>,<NA>,BAL,SEA,0.699,0.059

In [64]:
df.groupby('events')['woba_value'].mean()

events
catcher_interf                    0.7
double                           1.25
double_play                       0.0
field_error                       0.9
field_out                         0.0
fielders_choice                   0.9
fielders_choice_out               0.0
force_out                         0.0
grounded_into_double_play         0.0
hit_by_pitch                      0.7
home_run                          2.0
intent_walk                       0.4
sac_fly                           0.0
single                            0.9
strikeout                    0.002834
strikeout_double_play             0.0
triple                            1.6
truncated_pa                      0.0
walk                              0.7
Name: woba_value, dtype: Float64